name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.10.0

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          VITE_TARGET_CHAIN_ID: ${{ secrets.VITE_TARGET_CHAIN_ID }}
          VITE_DEFAULT_CURRENCY: ${{ secrets.VITE_DEFAULT_CURRENCY }}
          VITE_CURRENCY_DECIMALS: ${{ secrets.VITE_CURRENCY_DECIMALS }}

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/sharkcat/onlyarts-fe/deploy"
          strip_components: 1
          rm: true
          overwrite: true

      - name: Restart Nginx (optional)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/sharkcat/onlyarts-fe/deploy
            cp /var/www/sharkcat/onlyarts-fe/.env .
            sudo systemctl restart nginx
